# Generated by Django 4.2.1 on 2023-06-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomservice',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='roomservice',
            name='image',
            field=models.ImageField(blank=True, upload_to='about_me/awards/%Y/%m/%d'),
        ),
    ]
