# Generated by Django 4.2.3 on 2023-07-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_service', '0012_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='midia/image/'),
        ),
        migrations.AlterField(
            model_name='roomservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='midia/image/'),
        ),
    ]
