# Generated by Django 4.2.1 on 2023-06-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_service', '0002_roomservice_created_at_roomservice_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomservice',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
