# Generated by Django 4.2.1 on 2023-06-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_service', '0004_alter_roomservice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomservice',
            name='image',
            field=models.ImageField(blank=True, upload_to='midia/image/'),
        ),
    ]
