# Generated by Django 4.2.1 on 2023-06-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_service', '0005_alter_roomservice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomservice',
            name='category',
            field=models.CharField(choices=[('FNB', 'Food & Beverage'), ('BAS', 'Bath Amenity'), ('BED', 'Bedclothes'), ('ETC', 'Etc')], default='FNB', max_length=20),
        ),
    ]
