# Generated by Django 4.2.1 on 2023-06-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_service', '0008_alter_roomservice_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomservice',
            name='Request',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
