# Generated by Django 4.2.3 on 2023-08-02 10:52

from django.db import migrations, models
import room_service.models


class Migration(migrations.Migration):

    dependencies = [
        ('room_service', '0014_alter_product_image_alter_roomservice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=room_service.models.get_upload_to),
        ),
        migrations.AlterField(
            model_name='roomservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=room_service.models.get_upload_to),
        ),
    ]
